class mediawiki::params {

  $options = {
    'wgSitename'                     => 'media wiki',
    'wgMetaNamespace'                => 'media_wiki',
    'wgScriptPath'                   => '',
    'wgScriptExtension'              => '.php',
    'wgServer'                       => 'http://mediawiki.example.com',
    'wgStylePath'                    => '$wgScriptPath/skins',
    'wgLogo'                         => '$wgStylePath/common/images/wiki.png',
    'wgEnableEmail'                  => 'true',
    'wgEnableUserEmail'              => 'true',
    'wgEmergencyContact'             => 'contact@mediawiki.example.com',
    'wgPasswordSender'               => 'contact@mediawiki.example.com',
    'wgEnotifUserTalk'               => 'false',
    'wgEnotifWatchlist'              => 'false',
    'wgEmailAuthentication'          => 'true',
    'wgDBtype'                       => 'mysql',
    'wgDBserver'                     => '127.0.0.1',
    'wgDBname'                       => 'mediawiki',
    'wgDBuser'                       => 'root',
    'wgDBpassword'                   => 'password',
    'wgDBprefix'                     => '',
    'wgDBTableOptions'               => 'ENGINE=InnoDB, DEFAULT CHARSET=utf8',
    'wgDBmysql5'                     => 'false',
    'wgMainCacheType'                => 'CACHE_NONE',
    'wgMemCachedServers'             => 'array()',
    'wgEnableUploads'                => 'false',
    'wgUseImageMagick'               => 'true',
    'wgUseInstantCommons'            => 'false',
    'wgShellLocale'                  => 'en_US.utf8',
    'wgHashedUploadDirectory'        => 'false',
    'wgCacheDirectory'               => '$IP/cache',
    'wgLanguageCode'                 => 'en',
    'wgSecretKey'                    => 'ec916a1a2f41a4c1fb46d46a1ae72fd7015130d94ac80fcc33bcbcf2a46b6c2d',
    'wgUpgradeKey'                   => 'd21850fff5f91476',
    'wgDefaultSkin'                  => 'vector',
    'wgRightsPage'                   => '',
    'wgRightsUrl'                    => '',
    'wgRightsText'                   => '',
    'wgRightsIcon'                   => '',
    'wgDiff3'                        => '/usr/bin/diff3',
    'wgResourceLoaderMaxQueryLength' => '-1',
  }

}
